title: Connor Williams
email: willcon@umich.edu

baseurl: "" 
url: "https://minisolarclown.github.io" 

title_image: connor.jpg
google_scholar_link: "https://scholar.google.com/citations?user=JF5Jl6EAAAAJ&hl=en"
theme: null

